### ISSUE TITLE
Implement `Debug` & `Display` for `MontgomeryBackendPrimeField`.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambdaworks#203]
Instead of using derive, lets implement `Debug` & `Display` traits for `MontgomeryBackendPrimeField`. It should print the `representative` of the value in decimal format.

Example:
```
let one = U256MontgomeryTwoAdicPrimeField::one();
println!("one: {:?}", one); // prints "1"
```

**Comment by tcoratger** [comment]
@mpaulucci In the case you mentioned here, the result of all the operations related to the implementation of the `IsField` trait applied to the `MontgomeryBackendPrimeField<M, NUM_LIMBS>` structure are always expressed as a type `BaseType = UnsignedInteger<NUM_LIMBS>` for this particular Montgomery prime field.

The implementation of the `Debug` trait should therefore focus on the structure `UnsignedInteger<NUM_LIMBS>` itself rather than on the structure `MontgomeryBackendPrimeField<M, NUM_LIMBS>` that is ultimately not used in the result, WDT?
