### ISSUE TITLE
Iai PR benchmarks don't show the difference with main

### ISSUE THREAD

**Issue by xqft** [lambdaclass/lambdaworks#307]
Iai benchmarks should show improvements/regressions between main and the to-merge branch.

Also consider changing to [iai-callgrind](https://github.com/Joining7943/iai-callgrind), should be pretty straightforward. @Oppen do you know how does [calliper](https://github.com/osiewicz/calliper/) compare with iai-callgrind?

**Comment by Oppen** [comment]
The workflow as is doesn't publish the results (you can look for inspiration to make it post a comment [here](https://github.com/lambdaclass/cairo-rs/blob/main/.github/workflows/hyperfine.yml#L166-L199)) if that's what the issue is about. You can already look for those in the workflow logs. Not too user friendly, but at the time I did it we had a serious issue with pipeline run times using criterion and I prioritized having something useful quickly rather than feed my perfectionism.

I haven't tried either iai-callgrind (I knew there was an issue requesting migration to callgrind upstream, but I find it odd and slightly sad that someone went through the forking path rather than sending PRs, and I never found out) nor calliper (I remember the name tho, so I may have studied it, I don't know).
I'll try those in cairo-rs soon enough and come back with opinions.

**Comment by Oppen** [comment]
If you want to explore more options, there's an extension for criterion that uses `perf` on Linux. That can be used to more or less emulate the logic IAI uses as it queries cache hits and misses much like Valgrind does, but from hardware counters in non-emulated runs (it's faster, but more dependant on the actual machine, while still being less subject to random noise than wall time).

**Comment by Oppen** [comment]
During a little query (which I'll do more in depth in the weekend, right now I need to focus on automating the release process for cairo) I found this little gem that you may find interesting: https://crates.io/crates/criterion-cuda

**Comment by xqft** [comment]
Yep I knew about criterion-cuda, it seems really nice. Thank you so much for all the info! I asked you about calliper because I saw that you contributed to it some time ago. I think iai-callgrind was made from a fork because there's a one year old PR for using callgrind in iai and never got any feedback, also the last commit was three years ago, the author (the same one as criterion) doesn't have any public activity since 2022, they made iai as an experiment and maybe have no intention of continuing its development

**Comment by Oppen** [comment]
I contributed to calliper? Wow, I didn't remember that.

**Comment by Oppen** [comment]
> they made iai as an experiment and maybe have no intention of continuing its development

I was aware of this part. He planned on integrating the functionality to criterion back then.

**Comment by MegaRedHand** [comment]
> The workflow as is doesn't publish the results (...) if that's what the issue is about. You can already look for those in the workflow logs.

Note: [what shows in those](https://github.com/lambdaclass/lambdaworks/actions/runs/4952184439/jobs/8858157244?pr=336#step:6:350) are the _PR_'s results, not _main_'s
