### ISSUE TITLE
Move FFT to math and separate GPU folder and put parts inside FFT and MSM

### ISSUE THREAD

**Issue by diegokingston** [lambdaclass/lambdaworks#344]

**Comment by mpaulucci** [comment]
Update on this issue. I worked on https://github.com/lambdaclass/lambdaworks/pull/424 but unfortunately some work that is already in `main` was rolled back. 

There are two courses of action moving forward:

Continue working on #424. This will mean that we have to re-introduce the changes that were swallowed. This is not as easy as cherry-picking each commit and resolving conflicts, since a lot of files were moved around. 

Discard #424 and start from scratch. If this is decided then the recommended steps are:
- Decouple the `gpu` common abstractions from the specific implementations. Move specific functions like `radix2_dit_butterfly` are moved to a separate file.
- Make sure the `gpu` folder only has the generic functions, like here: https://github.com/lambdaclass/lambdaworks/tree/f632ee0418113df469edc412c84b7b44ee050359/gpu/src    
- Move all the specific functions to a new folder inside `math` like on #424 .
- Move benchmarks to `math`.
